image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS -B org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy -DaltSnapshotDeploymentRepository=snapshots::default::${env.MAVEN_REPO_URL}/libs-snapshot-local -DaltReleaseDeploymentRepository=central::default::${env.MAVEN_REPO_URL}/libs-release-local
  only:
    - master

traydeploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS -B clean test package org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy -DaltReleaseDeploymentRepository=bintray-gamer4life-CatUtils::default::https://api.bintray.com/maven/gamer4life/CatUtils/CatUtils/;publish=1
