image: maven:latest

before_script:
  - export M2_HOME=/usr/share/maven
  - gpg -v --import <(echo "$GPG_KEY")
  - export GPG_TTY=$(tty)
  - gpg --batch --allow-secret-key-import --import <(echo "$GPG_PRIVATE_KEY")

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode -Dsettings.security=.m2/settings-security.xml -DuniqueVersion=false"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  VERSION: 1.4.0

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile package

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

# deploy:
#   stage: deploy
#   script:
#     - mvn $MAVEN_CLI_OPTS --batch-mode -B clean install org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy -DaltSnapshotDeploymentRepository=snapshots::default::${MAVEN_REPO_URL}/libs-snapshot-local -DaltReleaseDeploymentRepository=central::default::${MAVEN_REPO_URL}/libs-release-local
#   only:
#     - master

tray-deploy:
  stage: deploy
  script:
    - chmod +x ./scripts/tray-deploy.sh
    - ./scripts/tray-deploy.sh $VERSION
  only:
    - master

# jfrog-deploy:
#   stage: deploy
#   script:
#     - curl -fL https://getcli.jfrog.io | sh
#     - ./jfrog rt c ghq --interactive=false --url='https://ghq.jfrog.io/ghq/' --user='deploy-bot' --password='meowcatnip'
#     - ./jfrog rt mvn "${MAVEN_CLI_OPTS} clean install" --build-name CIBuild --build-number $CI_JOB_ID
#     - ./jfrog rt bce CIBuild $CI_JOB_ID
#     - ./jfrog rt bp CIBuild $CI_JOB_ID

central-deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS clean install deploy #org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy -DaltSnapshotDeploymentRepository=ossrh::default::https://oss.sonatype.org/content/repositories/snapshots -DaltReleaseDeploymentRepository=ossrh::default::https://oss.sonatype.org/service/local/staging/deploy/maven2/
  only:
    - master
