name: CatUtils
main: io.github.gamer4life1.CatUtils.Main
version: v1.2
commands:
  heal:
    description: Heals the player
    permission: catutils.heal
    usage: /heal
  feed:
    description: Feeds the player
    permission: catutils.feed
    usage: /feed
  fly:
    description: Toggles fly mode
    permission: catutils.fly
    usage: /fly