name: CatUtils
main: io.github.gamercatorg.CatUtils.Main
version: v1.4.0-SNAPSHOT
commands:
  heal:
    description: Heals the player
    permission: catutils.heal
    usage: /heal
  feed:
    description: Feeds the player
    permission: catutils.feed
    usage: /feed
  fly:
    description: Toggles fly mode
    permission: catutils.fly
    usage: /fly
  tl:
    description: Adds levitation efect
    permission: catutils.levitation
    usage: /tl
